import json
import math

# --- Constants ---
TERRAIN_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_data.js'
OUTPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\perimeter_sides.js'

# --- Helpers ---
def haversine(lat1, lon1, lat2, lon2):
    R = 6371000
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi/2)**2 + math.cos(phi1)*math.cos(phi2)*math.sin(dlambda/2)**2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))

def calculate_midpoint(p1, p2):
    return [(p1[0] + p2[0])/2, (p1[1] + p2[1])/2] # lon, lat

def main():
    print("Loading Perimetro...")
    with open(TERRAIN_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
        json_str = content.replace('const TERRAIN_ROADS =', '').strip().rstrip(';')
        terrain_data = json.loads(json_str)
    
    perimetro_coords = [] # [lon, lat]
    for feat in terrain_data['features']:
        if feat['properties'].get('layer') == 'perimetro':
            coords = feat['geometry']['coordinates']
            geom_type = feat['geometry']['type']
            if geom_type == 'Polygon':
                perimetro_coords = coords[0]
            elif geom_type == 'LineString':
                perimetro_coords = coords
            else:
                perimetro_coords = coords
            break
            
    if not perimetro_coords:
        print("Error: Could not find 'perimetro' layer.")
        return

    # Deduplicate closed ring
    if len(perimetro_coords) > 1 and perimetro_coords[0] == perimetro_coords[-1]:
        perimetro_coords = perimetro_coords[:-1]
        
    if len(perimetro_coords) != 3:
        print(f"Warning: Perimeter has {len(perimetro_coords)} vertices, expected 3 (Triangle). Proceeding anyway.")

    # Identify Vertices
    # Based on coordinates analysis:
    # V1 (NE - Start of Green Route): Max Latitude (least negative), Max Longitude (least negative) approx.
    # V2 (NW - Sea End): Similar Lat to V1, Min Longitude (most negative).
    # V3 (S - South Tip): Min Latitude (most negative).

    # Sort by Latitude (South to North)
    sorted_by_lat = sorted(perimetro_coords, key=lambda p: p[1])
    
    v3 = sorted_by_lat[0] # Most South
    northern_points = sorted_by_lat[1:]
    
    # Sort northern points by Longitude (West to East)
    northern_points.sort(key=lambda p: p[0])
    
    v2 = northern_points[0] # West (Sea)
    v1 = northern_points[1] # East (Green Route Start)
    
    print(f"V1 (NE - Start): {v1}")
    print(f"V2 (NW - Sea): {v2}")
    print(f"V3 (S - South): {v3}")
    
    # Define Sides
    # Lado A (Norte): V1 -> V2 (Green Route Ext)
    # Lado B (Este): V1 -> V3 (Land side)
    # Lado C (Oeste): V2 -> V3 (Sea side)
    
    sides = []
    
    # Side A
    len_a = haversine(v1[1], v1[0], v2[1], v2[0])
    sides.append({
        "id": "A",
        "name": "Lado A (Extensión)",
        "coords": [v1, v2],
        "length_m": len_a,
        "color": "#10b981", # Green like route
        "desc": "Extensión Ruta Verde"
    })
    
    # Side B
    len_b = haversine(v1[1], v1[0], v3[1], v3[0])
    sides.append({
        "id": "B",
        "name": "Lado B (Este)",
        "coords": [v1, v3],
        "length_m": len_b,
        "color": "#f59e0b", # Amber/Orange
        "desc": "Límite Este (Tierra)"
    })
    
    # Side C
    len_c = haversine(v2[1], v2[0], v3[1], v3[0])
    sides.append({
        "id": "C",
        "name": "Lado C (Oeste)",
        "coords": [v2, v3],
        "length_m": len_c,
        "color": "#3b82f6", # Blue
        "desc": "Frente al Mar"
    })
    
    # Build GeoJSON
    features = []
    
    for s in sides:
        km = s['length_m'] / 1000.0
        label = f"{s['name']}: {km:.2f} km"
        
        feat = {
            "type": "Feature",
            "properties": {
                "name": label,
                "side_id": s['id'],
                "length_km": round(km, 2),
                "description": s['desc'],
                "stroke": s['color']
            },
            "geometry": {
                "type": "LineString",
                "coordinates": s['coords'] # [lon, lat]
            }
        }
        features.append(feat)
        print(f"{s['name']}: {km:.2f} km")

    geojson = {
        "type": "FeatureCollection",
        "features": features
    }
    
    js_content = f"""
// Auto-generated by analyze_perimeter_sides.py
const PERIMETER_SIDES_GEOJSON = {json.dumps(geojson, indent=4)};
"""

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
