import json
import re
import math

def haversine(coord1, coord2):
    # lon, lat
    lon1, lat1 = coord1
    lon2, lat2 = coord2
    R = 6371000  # radius of Earth in meters
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2)**2
    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))

js_path = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\new_green_route.js'
with open(js_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Extract GeoJSON Coordinates
geo_match = re.search(r'"coordinates":\s*\[(.*?)\]', content, re.DOTALL)
if not geo_match:
    print("Coordinates not found")
    exit(1)

coords_str = geo_match.group(1)
# Correct formatting to make it a valid JSON array of arrays
coords_list = json.loads("[" + coords_str + "]")

# 2. Extract Existing Points
points_match = re.search(r'const NEW_GREEN_ROUTE_POINTS = \[(.*?)\];', content, re.DOTALL)
if not points_match:
    print("Points not found")
    exit(1)

points_str = "[" + points_match.group(1) + "]"
existing_points = json.loads(points_str)

# 3. Find the last point in the coordinates list
last_point_data = existing_points[-1]
last_coords_js = [last_point_data['coords'][1], last_point_data['coords'][0]] # [lon, lat]

try:
    start_idx = coords_list.index(last_coords_js)
except ValueError:
    # Try finding the closest point
    min_dist = 999999
    start_idx = -1
    for i, c in enumerate(coords_list):
        d = haversine(c, last_coords_js)
        if d < min_dist:
            min_dist = d
            start_idx = i
    print(f"Closest match found at index {start_idx} with dist {min_dist}m")

# 4. Generate new points for the remainder
current_km = last_point_data['km']
last_c = coords_list[start_idx]

new_points_to_add = []
for i in range(start_idx + 1, len(coords_list)):
    current_c = coords_list[i]
    dist = haversine(last_c, current_c)
    current_km += dist / 1000.0
    
    # Create point object
    # We'll use the last known alt (498.0) and slope 0 for simplicity if no data
    p = {
        "name": f"KM {round(current_km*2)/2}" if (round(current_km*10) % 5 == 0) else "",
        "coords": [current_c[1], current_c[0]], # lat, lon
        "alt": last_point_data['alt'],
        "slope": 0.0,
        "km": round(current_km, 3)
    }
    # Only show KM label if it's a "clean" 0.5 increment and hasn't been shown
    if p["name"] == last_point_data["name"]: p["name"] = ""
    
    new_points_to_add.append(p)
    last_c = current_c

# 5. Append and rewrite
full_points = existing_points + new_points_to_add
points_json = json.dumps(full_points, indent=4)

# Reconstruct file
# Preserve the header and GeoJSON
geojson_match = re.search(r'(const NEW_GREEN_ROUTE_GEOJSON = \{.*?\};)', content, re.DOTALL)
geojson_part = geojson_match.group(1)

new_content = f"""
// Auto-generated by Antigravity - Extended Labels
{geojson_part}

const NEW_GREEN_ROUTE_POINTS = {points_json};
"""

with open(js_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Added {len(new_points_to_add)} new labels. Path updated.")
