import json
import re
import math

def haversine(coord1, coord2):
    lon1, lat1 = coord1
    lon2, lat2 = coord2
    R = 6371000
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2)**2
    return 2 * R * math.atan2(math.sqrt(a), math.sqrt(1 - a))

js_path = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\new_green_route.js'
with open(js_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Extract GeoJSON carefully
# Find the start of the object { after NEW_GREEN_ROUTE_GEOJSON = 
geo_start = content.find('const NEW_GREEN_ROUTE_GEOJSON = ') + len('const NEW_GREEN_ROUTE_GEOJSON = ')
# Find the end of that object (search for };)
geo_end = content.find('};', geo_start) + 1
geo_str = content[geo_start:geo_end].strip()
geojson = json.loads(geo_str)
coords_list = geojson['features'][0]['geometry']['coordinates']

# 2. Extract Existing Points carefully
points_start = content.find('const NEW_GREEN_ROUTE_POINTS = ') + len('const NEW_GREEN_ROUTE_POINTS = ')
points_end = content.find('];', points_start) + 1
points_str = content[points_start:points_end].strip()
existing_points = json.loads(points_str)

# 3. Find the last point matches in coords_list
last_point_data = existing_points[-1]
last_coords_js = [last_point_data['coords'][1], last_point_data['coords'][0]] # [lon, lat]

min_dist = 999999
start_idx = -1
for i, c in enumerate(coords_list):
    d = haversine(c, last_coords_js)
    if d < min_dist:
        min_dist = d
        start_idx = i

print(f"Syncing labels starting at index {start_idx} (dist: {min_dist:.2f}m)")

# 4. Generate new points
current_km = last_point_data['km']
last_c = coords_list[start_idx]

new_points_to_add = []
# Pattern KM: every 0.1km for granularity or every 0.5km for labels?
# Original had KM labels every 0.5km usually.

for i in range(start_idx + 1, len(coords_list)):
    current_c = coords_list[i]
    dist = haversine(last_c, current_c)
    current_km += dist / 1000.0
    
    # We want a point every ~100m like the original to show tooltips
    # And a label name every 0.5km
    
    # Add point if distance since last added point is > 90m (to match previous density)
    # Actually, let's just add all points to be safe, Leaflet handles it.
    
    is_five_hundred = (round(current_km * 10) % 5 == 0)
    label_name = f"KM {round(current_km * 2) / 2:.1f}" if is_five_hundred else ""
    
    # Avoid duplicate labels
    if label_name and any(p['name'] == label_name for p in existing_points + new_points_to_add):
        label_name = ""

    p = {
        "name": label_name,
        "coords": [current_c[1], current_c[0]],
        "alt": last_point_data['alt'], # Keep last alt or interpolate if we had it
        "slope": 0.0,
        "km": round(current_km, 3)
    }
    
    new_points_to_add.append(p)
    last_c = current_c

# 5. Save
full_points = existing_points + new_points_to_add

new_content = f"""
// Auto-generated by Antigravity - Final Label Extension
const NEW_GREEN_ROUTE_GEOJSON = {json.dumps(geojson, indent=4)};

const NEW_GREEN_ROUTE_POINTS = {json.dumps(full_points, indent=4)};
"""

with open(js_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Success! Added {len(new_points_to_add)} points. Green Route fully labeled.")
