-- Script para crear la tabla de seguimiento de campo en Supabase
-- Ejecuta esto en el SQL Editor de tu consola de Supabase

CREATE TABLE IF NOT EXISTS public.field_tracking (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    trip_id text not null,        -- Identificador del viaje (ej: 'Marcona_Marzo_2026')
    latitude double precision not null,
    longitude double precision not null,
    accuracy double precision,    -- Precisión del GPS en metros
    user_name text not null,      -- Identificador de quién está grabando (ej: 'Camion_01', 'Supervisor')
    elevation double precision    -- Altura sobre el nivel del Mar (MSNM)
);

-- Habilitar RLS
ALTER TABLE public.field_tracking ENABLE ROW LEVEL SECURITY;

-- Políticas de acceso para que la App pueda insertar datos
CREATE POLICY "Permitir inserción pública" 
ON public.field_tracking FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir lectura pública" 
ON public.field_tracking FOR SELECT 
USING (true);

-- Indice para mejorar consultas por viaje y fecha
CREATE INDEX IF NOT EXISTS idx_tracking_trip_date ON public.field_tracking (trip_id, created_at);
