-- 1. Crear la nueva tabla con la columna de elevación
CREATE TABLE public.field_tracking_elevation (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    trip_id text not null,
    latitude double precision not null,
    longitude double precision not null,
    accuracy double precision,
    user_name text not null,
    elevation double precision -- Nuestra nueva columna
);

-- 2. Migrar los datos de la tabla original a la nueva
INSERT INTO public.field_tracking_elevation (created_at, trip_id, latitude, longitude, accuracy, user_name)
SELECT created_at, trip_id, latitude, longitude, accuracy, user_name
FROM public.field_tracking;

-- 3. Habilitar RLS y políticas
ALTER TABLE public.field_tracking_elevation ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir inserción pública v2" 
ON public.field_tracking_elevation FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir lectura pública v2" 
ON public.field_tracking_elevation FOR SELECT 
USING (true);

-- 4. Índice para rendimiento
CREATE INDEX idx_tracking_elev_trip_date ON public.field_tracking_elevation (trip_id, created_at);
