import json
import math
import requests
import time
import os

# --- CONFIGURATION ---
GRID_SPACING_METERS = 50

# PERIMETER COORDINATES (Petral Triangle)
V1 = [-75.25695083552709, -15.165498334382889] # NE
V2 = [-75.26825393885237, -15.172534472456562] # NW
V3 = [-75.23798892224755, -15.197477563030073] # S

OUTPUT_FILE = 'terrain_mesh_3d.js'
CACHE_FILE = 'terrain_elevation_cache_alt.json' # Separate cache for safety

def point_in_triangle(pt, v1, v2, v3):
    def sign(p1, p2, p3):
        return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1])
    
    d1 = sign(pt, v1, v2)
    d2 = sign(pt, v2, v3)
    d3 = sign(pt, v3, v1)
    
    has_neg = (d1 < 0) or (d2 < 0) or (d3 < 0)
    has_pos = (d1 > 0) or (d2 > 0) or (d3 > 0)
    
    return not (has_neg and has_pos)

def get_elevation_batch_open_meteo(locations):
    """
    Fetch elevations from Open-Meteo for a list of (lon, lat).
    NOTE: Input locations here are [lon, lat], but API expects lat,lon.
    """
    base_url = "https://api.open-meteo.com/v1/elevation"
    
    # Process in chunks to respect URL length / API limits
    # Smaller chunks for repair to be agile
    
    # Just handle one batch call logic here, caller handles looping
    # Actually, to fit the existing signature flow, let's process the input list fully
    
    lats = [f"{p[1]:.6f}" for p in locations]
    lons = [f"{p[0]:.6f}" for p in locations]
    
    url = f"{base_url}?latitude={','.join(lats)}&longitude={','.join(lons)}"
    
    try:
        resp = requests.get(url, timeout=10)
        data = resp.json()
        
        if 'elevation' in data:
            return data['elevation']
        elif 'error' in data:
            print(f"    (Open-Meteo Error: {data.get('reason')})")
            return None # Explicit failure
        else:
            return None
            
    except Exception as e:
        print(f"    (Open-Meteo Request Failed: {e})")
        return None

def get_elevation_batch_open_elevation(locations):

    """
    Fetches elevation from Open-Elevation API (POST request).
    locations: list of [lon, lat]
    """
    # Format for Open-Elevation: {"locations": [{"latitude": 10, "longitude": 10}, ...]}
    payload = {
        "locations": [{"latitude": p[1], "longitude": p[0]} for p in locations]
    }
    
    url = "https://api.open-elevation.com/api/v1/lookup"
    
    for attempt in range(3):
        try:
            resp = requests.post(url, json=payload, headers={'Content-Type': 'application/json'}, timeout=30)
            
            if resp.status_code == 200:
                data = resp.json()
                # Extract results in order
                results = data.get('results', [])
                elevations = [r['elevation'] for r in results]
                
                if len(elevations) != len(locations):
                    print(f"  ⚠ Mismatch: Sent {len(locations)}, got {len(elevations)}")
                    return [0] * len(locations) # Fail safe
                
                return elevations
            else:
                print(f"  HTTP Error {resp.status_code}: {resp.text[:100]}")
                time.sleep(2)
        
        except Exception as e:
            print(f"  Request failed (Attempt {attempt+1}): {e}")
            time.sleep(2)
            
    return [0] * len(locations) # Return 0s if all retries fail

def save_terrain_js(g_points, z_values, valid_points_subset=None, zero_points_subset=None, wall_data=None, stats=None):
    safe_z = [z if z is not None else 0 for z in z_values]
    x_c = [p[0] for p in g_points]
    y_c = [p[1] for p in g_points]
    
    if valid_points_subset is None: valid_points_subset = {"x":[], "y":[], "z":[]}
    if zero_points_subset is None: zero_points_subset = {"x":[], "y":[], "z":[]}
    if zero_points_subset is None: zero_points_subset = {"x":[], "y":[], "z":[]}
    if wall_data is None: wall_data = {"x":[], "y":[], "z":[]}
    if stats is None: stats = {}
    
    # Handle Hex Data (passed via simple dict or we verify later)
    # Actually, pass hex data via 'wall_data' structure if convenient or a new one
    # Let's assume wall_data might assume 'hex' dictionary inside if we pass it
    hex_data = stats.get('hex_wall', None) # Extract from stats hack or pass argument proper
    
    js_content = f"""
// Auto-generated by generate_terrain_alternative.py
// API: Open-Elevation
// Updated: {time.strftime('%H:%M:%S')}
const TERRAIN_MESH_DATA = {{
    x: {json.dumps(x_c)},
    y: {json.dumps(y_c)},
    z: {json.dumps(safe_z)},
    
    valid_pts: {json.dumps(valid_points_subset)},
    zero_pts: {json.dumps(zero_points_subset)},
    
    wall_x: {json.dumps(wall_data['x'])},
    wall_y: {json.dumps(wall_data['y'])},
    wall_z: {json.dumps(wall_data['z'])},
    
    hex_x: {json.dumps(hex_data['x'] if hex_data else [])},
    hex_y: {json.dumps(hex_data['y'] if hex_data else [])},
    hex_z: {json.dumps(hex_data['z'] if hex_data else [])},
    
    stats: {json.dumps(stats)},
    
    type: 'mesh3d',
    intensity: {json.dumps(safe_z)},
    colorscale: 'Earth'
}};
"""

    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(js_content)
        # print(f"  -> JS Updated.")
    except Exception as e:
        print(f"  ⚠ Failed to update JS: {e}")

def main():
    print("=" * 60)
    print("GENERACIÓN DE MALLA 3D - PLAN B (Open-Elevation)")
    print("=" * 60)
    
    # 1. Grid Generation (Same as before)
    # Extended Box (+1km N/E)
    lons = [V1[0], V2[0], V3[0]]
    lats = [V1[1], V2[1], V3[1]]
    
    min_lon, max_lon = min(lons), max(lons)
    min_lat, max_lat = min(lats), max(lats)
    
    # Extension in Degrees approx
    ext_deg = 1000 / 111132 
    max_lat += ext_deg
    max_lon += ext_deg
    
    lat_step = (GRID_SPACING_METERS / 111132) 
    avg_lat = (min_lat + max_lat) / 2
    lon_step = (GRID_SPACING_METERS / (111320 * math.cos(math.radians(avg_lat))))
    
    grid_points = []
    curr_lat = max_lat
    while curr_lat >= min_lat:
        curr_lon = min_lon
        while curr_lon <= max_lon:
            grid_points.append([curr_lon, curr_lat])
            curr_lon += lon_step
        curr_lat -= lat_step
        
    print(f"Grid Points: {len(grid_points)}")
    
    # 2. Caching Setup
    elevation_cache = {}
    if os.path.exists(CACHE_FILE):
        try:
            with open(CACHE_FILE, 'r') as f:
                elevation_cache = json.load(f)
            print(f"Loaded Cache: {len(elevation_cache)} items")
        except: pass
        
    def save_cache():
        with open(CACHE_FILE, 'w') as f:
            json.dump(elevation_cache, f)

    def get_key(lat, lon):
        return f"{lat:.6f}_{lon:.6f}"

    # 3. Fetch Loop
    BATCH_SIZE = 100 # Open-Elevation can handle reasonable batches
    all_elevations = []
    points_to_fetch = []
    points_indices = []
    
    # Pre-fill
    for i, pt in enumerate(grid_points):
        k = get_key(pt[1], pt[0])
        val = elevation_cache.get(k, 0)
        
        if val != 0:
            all_elevations.append(val)
        else:
            all_elevations.append(None)
            points_to_fetch.append(pt)
            points_indices.append(i)
            
    print(f"Points to fetch: {len(points_to_fetch)}")
    
    if points_to_fetch:
        for i in range(0, len(points_to_fetch), BATCH_SIZE):
            batch = points_to_fetch[i:i+BATCH_SIZE]
            indices = points_indices[i:i+BATCH_SIZE]
            
            # Fetch
            new_elevs = get_elevation_batch_open_elevation(batch)
            
            # Update
            for j, val in enumerate(new_elevs):
                g_idx = indices[j]
                all_elevations[g_idx] = val
                
                # Cache
                pt = batch[j]
                elevation_cache[get_key(pt[1], pt[0])] = val
            
            # Progress output
            valid_count = len([x for x in new_elevs if x != 0])
            print(f"Batch {i//BATCH_SIZE + 1}: {valid_count}/{len(batch)} valid.")
            
            if i % 500 == 0:
                save_cache()
                # Quick JS update for viz
                save_terrain_js(grid_points, all_elevations, stats={"status": f"Fetching {i}/{len(points_to_fetch)}"})
                
            time.sleep(0.5) # Polite delay
            
        save_cache()

    # Fill remaining Nones
    all_elevations = [e if e is not None else 0 for e in all_elevations]

    # --- REPAIR LOGIC (HYBRID: Uses Open-Meteo for repairs) ---
    def repair_zeros_hybrid(points, elevations, cache):
        # Load Confirmed Zeros (Points we queried and confirmed are valid 0 or valid data)
        CONFIRMED_ZEROS_FILE = 'confirmed_zeros.json'
        confirmed_zeros = set()
        if os.path.exists(CONFIRMED_ZEROS_FILE):
            try:
                with open(CONFIRMED_ZEROS_FILE, 'r') as f:
                    confirmed_zeros = set(json.load(f))
                print(f"  Loaded {len(confirmed_zeros)} confirmed zero/checked points.")
            except: pass

        def save_confirmed():
            with open(CONFIRMED_ZEROS_FILE, 'w') as f:
                json.dump(list(confirmed_zeros), f)

        # Identify gaps, EXCLUDING confirmed ones
        zero_indices = []
        for i, z in enumerate(elevations):
            if z == 0:
                pt = points[i]
                k = get_key(pt[1], pt[0])
                if k not in confirmed_zeros:
                    zero_indices.append(i)
        
        if not zero_indices: return elevations
        
        initial_count = len(zero_indices)
        print(f"\n{'!'*60}")
        print(f"HYBRID REPAIR: Switching to OPEN-METEO for {initial_count} gaps...")
        print(f"{'!'*60}")
        
        # We will loop until list is empty or max retries reached
        MAX_GLOBAL_ATTEMPTS = 5
        
        for attempt in range(MAX_GLOBAL_ATTEMPTS):
            if not zero_indices:
                print("  ✓ All gaps filled!")
                break
                
            print(f"  \n[Attempt {attempt+1}/{MAX_GLOBAL_ATTEMPTS}] Targeting {len(zero_indices)} points...")
            
            # Dynamic list strategy:
            # We iterate through the current zero_indices.
            # If we get a value, we update immediately.
            # Next global attempt will naturally only see remaining zeros.
            
            REPAIR_BATCH = 80 # Open-Meteo handles ~100 ok
            new_zeros = []
            
            for i in range(0, len(zero_indices), REPAIR_BATCH):
                batch_idxs = zero_indices[i:i+REPAIR_BATCH]
                batch_pts = [points[idx] for idx in batch_idxs]
                
                # Use Open-Meteo for repair
                new_vals = get_elevation_batch_open_meteo(batch_pts)
                
                if new_vals is None:
                    # Request failed totally - keep as targets for next time
                    # Add all to new_zeros
                    new_zeros.extend(batch_idxs)
                    print(f"    Batch {i//REPAIR_BATCH + 1}: Failed (Network/Limit)")
                    time.sleep(5)
                    continue

                # If we are here, new_vals is a list of elevations (maybe 0s, but VALID 0s)
                batch_success = 0
                for k, val in enumerate(new_vals):
                    original_idx = batch_idxs[k]
                    pt = points[original_idx]
                    key = get_key(pt[1], pt[0])
                    
                    # Accept ANY value returned by successfull call
                    elevations[original_idx] = val
                    cache[key] = val
                    
                    # MARK AS CONFIRMED (So we never re-fetch this point)
                    confirmed_zeros.add(key)
                    batch_success += 1
                
                # Real-time feedback
                remaining = len(zero_indices) - (i + len(batch_pts)) # Approximate remaining in this pass
                print(f"    Batch {i//REPAIR_BATCH + 1}: Confirmed {batch_success} pts | Pending in this pass: {max(0, remaining)}")
                
                # Use Turbo-Updates for confirmed
                save_confirmed()
                
                # Polite wait for Open-Meteo rate limits (90 seconds as requested)
                print("    Waiting 90 seconds before next batch...")
                time.sleep(90) 
            
            # Save progress
            save_cache()
            save_terrain_js(grid_points, elevations, stats={"status": f"Repairing ({len(new_zeros)} left)"})
            
            # Update the target list for next pass
            if len(new_zeros) == len(zero_indices):
                print("    ⚠ No progress in this pass. Increasing wait time.")
                time.sleep(10)
            
            zero_indices = new_zeros
            
        return elevations

        return elevations

    all_elevations = repair_zeros_hybrid(grid_points, all_elevations, elevation_cache)

    # --- 5. HEX MESH WALL GENERATION ---
    def get_z_at_geo(lon, lat, grid_pts, z_vals, grid_w, grid_h, min_x, max_y, dx, dy):
        # Bilinear Interpolation
        # Grid loop: curr_lat start at max_lat, goes down (-dy)
        #            curr_lon start at min_lon, goes right (+dx)
        
        # Row (y): distance from max_lat
        r_f = (max_y - lat) / dy
        c_f = (lon - min_x) / dx
        
        r0 = int(r_f)
        c0 = int(c_f)
        
        # Clamp
        if r0 < 0: r0 = 0
        if r0 >= grid_h - 1: r0 = grid_h - 2
        if c0 < 0: c0 = 0
        if c0 >= grid_w - 1: c0 = grid_w - 2
        
        # Indices
        # idx = r * width + c
        i00 = r0 * grid_w + c0
        i01 = r0 * grid_w + (c0 + 1)
        i10 = (r0 + 1) * grid_w + c0
        i11 = (r0 + 1) * grid_w + (c0 + 1)
        
        if i11 >= len(z_vals): return 0
        
        z00 = z_vals[i00]
        z01 = z_vals[i01]
        z10 = z_vals[i10]
        z11 = z_vals[i11]
        
        # Local coords
        tr = r_f - r0
        tc = c_f - c0
        
        # Interpolate
        top = z00 * (1 - tc) + z01 * tc
        bot = z10 * (1 - tc) + z11 * tc
        return top * (1 - tr) + bot * tr

    def generate_hex_wall_3d(p_start, p_end, z_floor, z_start_ceil, z_end_ceil, u_global_offset=0.0):
        # Generate 3D line segments for a hex mesh on this vertical plane
        
        # 1. Plane UV basis
        # U: horizontal along wall (using u_global_offset to keep phase alignment)
        # V: vertical (Z)
        
        dist = math.sqrt((p_end[0]-p_start[0])**2 + (p_end[1]-p_start[1])**2) 
        # Convert dist to meters approx for hex sizing
        # lat avg
        lat_avg = (p_start[1] + p_end[1]) / 2
        deg_len = math.sqrt(((p_end[0]-p_start[0]) * 111320 * math.cos(math.radians(lat_avg)))**2 + ((p_end[1]-p_start[1])*111132)**2)
        
        if deg_len < 0.1: return [], [], []
        
        HEX_SIZE = 15.0 # meters
        
        u_len = deg_len
        v_start = z_start_ceil - z_floor
        v_end = z_end_ceil - z_floor
        max_v = max(v_start, v_end)
        
        lines_x = []
        lines_y = []
        lines_z = []
        
        # Hex Grid Logic (Honeycomb)
        w = math.sqrt(3) * HEX_SIZE # ~26m
        h = 2 * HEX_SIZE # 30m
        vert_dist = 0.75 * h # 22.5m
        
        # Grid range relative to GLOBAL offset
        # We need to cover the local range [u_global_offset, u_global_offset + u_len]
        
        start_u = u_global_offset
        end_u = u_global_offset + u_len
        
        # Determine cols range
        start_col = int(start_u / w) - 1
        end_col = int(end_u / w) + 2
        
        rows = int(max_v / vert_dist) + 1
        
        def get_geo(u_local, v):
            # Transform local (u_local, v) back to (lon, lat, z)
            # U_local is from 0 to u_len
            frac = u_local / u_len
            
            lon = p_start[0] + frac * (p_end[0] - p_start[0])
            lat = p_start[1] + frac * (p_end[1] - p_start[1])
            z = z_floor + v
            return lon, lat, z

        # Generate Hex edges
        for r in range(rows):
            yr = r * vert_dist
            offset_x = (w / 2.0) if (r % 2 == 1) else 0.0
            
            # Iterate cols based on global position
            for c in range(start_col, end_col):
                xc_global = c * w + offset_x
                
                # Convert to local U
                xc_local = xc_global - u_global_offset
                
                # Check rough bounds (optimization)
                if xc_local < -HEX_SIZE or xc_local > u_len + HEX_SIZE: continue
                
                # Points of a hex (Pointy Topped)
                pts = []
                for k in range(7):
                    ang = math.radians(30 + 60 * k)
                    px = xc_local + HEX_SIZE * math.cos(ang)
                    py = yr + HEX_SIZE * math.sin(ang)
                    pts.append((px, py))
                
                # Clip and Add lines
                for k in range(6):
                    p1 = pts[k]
                    p2 = pts[k+1]
                    
                    # 1. Horizontal Clipping (Local Segment)
                    # We only care about the part of the line INSIDE [0, u_len]
                    # Simple accept/reject is risky for continuity, but improved:
                    
                    # If both outside same side, skip
                    if (p1[0] < 0 and p2[0] < 0) or (p1[0] > u_len and p2[0] > u_len): continue
                    
                    # Clamp X to segment
                    x1_c = max(0, min(u_len, p1[0]))
                    x2_c = max(0, min(u_len, p2[0]))
                    
                    # If clamped interval is tiny, skip
                    if abs(x2_c - x1_c) < 0.01: continue
                    
                    # Interpolate Y (height) at clamped X
                    # Line eq: y = m*x + b
                    if abs(p2[0] - p1[0]) > 0.001:
                        m = (p2[1] - p1[1]) / (p2[0] - p1[0])
                        y1_c = p1[1] + m * (x1_c - p1[0])
                        y2_c = p2[1] + m * (x2_c - p1[0])
                    else:
                        y1_c = p1[1]
                        y2_c = p2[1]
                    
                    # 2. Vertical Clipping (Ceiling) aka Clamping
                    # Ceiling func
                    def get_ceil(u):
                        return (z_start_ceil * (1 - u/u_len) + z_end_ceil * (u/u_len)) - z_floor
                    
                    ceil1 = get_ceil(x1_c)
                    ceil2 = get_ceil(x2_c)
                    
                    # If completely above ceiling, skip
                    if y1_c > ceil1 and y2_c > ceil2: continue
                    # If completely below floor, skip
                    if y1_c < 0 and y2_c < 0: continue
                    
                    # Clamp Y to ceiling/floor
                    y1_final = max(0, min(ceil1, y1_c))
                    y2_final = max(0, min(ceil2, y2_c))
                    
                    # Generate 3D Coords
                    g1 = get_geo(x1_c, y1_final)
                    g2 = get_geo(x2_c, y2_final)
                    
                    lines_x.extend([g1[0], g2[0], None])
                    lines_y.extend([g1[1], g2[1], None])
                    lines_z.extend([g1[2], g2[2], None])
                    
        return lines_x, lines_y, lines_z

    # Re-calc Grid Params for lookup
    grid_cols = int((max_lon - min_lon) / lon_step) + 1
    grid_rows = int((max_lat - min_lat) / lat_step) + 1
    
    hex_wall_data = {"x": [], "y": [], "z": []}
    
    # Process Perimeter
    perimeter = [V1, V2, V3]
    CUT_LEVEL_Z = 30.0
    
    # Lists to collect the EXACT perimeter boundary points
    # We will force-add these to the mesh to ensure it snaps to the wall
    perimeter_boundary_top = []    # For the Terrain Mesh (Natural Z)
    perimeter_boundary_bottom = [] # For the Floor Mesh (Z = 30)

    for i in range(3):
        start = perimeter[i]
        end = perimeter[(i+1)%3]
        
        # Sampling steps
        dist_deg = math.sqrt((start[0]-end[0])**2 + (start[1]-end[1])**2)
        steps = int(dist_deg * 111000 / 20) # Every 20m
        if steps == 0: steps = 1
        
        # Reset global offset for each NEW SIDE
        current_u_offset = 0.0
        
        for k in range(steps):
            f1 = k / steps
            f2 = (k+1) / steps
            
            p1 = [start[0] + f1*(end[0]-start[0]), start[1] + f1*(end[1]-start[1])]
            p2 = [start[0] + f2*(end[0]-start[0]), start[1] + f2*(end[1]-start[1])]
            
            # Calc segment length in meters for offset update
            lat_avg_seg = (p1[1] + p2[1]) / 2
            seg_len_deg_lon = (p2[0]-p1[0]) * 111320 * math.cos(math.radians(lat_avg_seg))
            seg_len_deg_lat = (p2[1]-p1[1]) * 111132
            seg_len_m = math.sqrt(seg_len_deg_lon**2 + seg_len_deg_lat**2)
            
            z1 = get_z_at_geo(p1[0], p1[1], grid_points, all_elevations, grid_cols, grid_rows, min_lon, max_lat, lon_step, lat_step)
            z2 = get_z_at_geo(p2[0], p2[1], grid_points, all_elevations, grid_cols, grid_rows, min_lon, max_lat, lon_step, lat_step)
            
            # Check if this segment requires a wall (Cut)
            # Logic: If Z > CUT_LEVEL, we are cutting.
            is_cut_1 = z1 > CUT_LEVEL_Z
            is_cut_2 = z2 > CUT_LEVEL_Z
            
            if is_cut_1 or is_cut_2:
                cutoff1 = max(z1, CUT_LEVEL_Z)
                cutoff2 = max(z2, CUT_LEVEL_Z)
                
                # PASS current_u_offset
                hx, hy, hz = generate_hex_wall_3d(p1, p2, CUT_LEVEL_Z, cutoff1, cutoff2, current_u_offset)
                hex_wall_data["x"].extend(hx)
                hex_wall_data["y"].extend(hy)
                hex_wall_data["z"].extend(hz)
                
                # Collect Boundary Points for Surgical Mesh Split
                # We add p1 and p2 to both lists
                # Top: Natural Z (or clamped if it dips?) - actually Natural Z is best for "Outside" mesh
                # But wait, if z1 < CUT_LEVEL, the wall height is 0. 
                # Let's use the 'cutoff' values which act as the wall top.
                
                perimeter_boundary_top.append([p1[0], p1[1], cutoff1])
                perimeter_boundary_top.append([p2[0], p2[1], cutoff2])
                
                perimeter_boundary_bottom.append([p1[0], p1[1], CUT_LEVEL_Z])
                perimeter_boundary_bottom.append([p2[0], p2[1], CUT_LEVEL_Z])
            
            # Advance offset
            current_u_offset += seg_len_m

    print(f"Generated Hex Wall Mesh: {len(hex_wall_data['x'])} vert points.")
    
    # --- 4. MESH GENERATION (GRID SNAPPING + EXPLICIT TRIANGULATION) ---
    # To avoid "Spilled Earth" (Delaunay filling the hole) and "Jagged Edges",
    # we will:
    # A. Snap grid points near the perimeter to the perimeter line.
    # B. Generate explicit grid triangles (i,j,k).
    # C. Filter triangles based on whether they are Inside or Outside the cut.

    # --- 3.5 STATISTICS (VOLUME) ---
    cell_area = GRID_SPACING_METERS * GRID_SPACING_METERS
    total_cut_volume = 0
    points_cut = 0
    
    for i, pt in enumerate(grid_points):
         z = all_elevations[i]
         if z is not None and z > CUT_LEVEL_Z:
             if point_in_triangle(pt, V1, V2, V3):
                 total_cut_volume += (z - CUT_LEVEL_Z) * cell_area
                 points_cut += 1

    print("Refining Mesh (Snapping & Triangulating)...")

    # Helper: Distance from point to segment
    def dist_sq_point_segment(px, py, x1, y1, x2, y2):
        l2 = (x1-x2)**2 + (y1-y2)**2
        if l2 == 0: return (px-x1)**2 + (py-y1)**2
        t = ((px-x1)*(x2-x1) + (py-y1)*(y2-y1)) / l2
        t = max(0, min(1, t))
        proj_x = x1 + t * (x2-x1)
        proj_y = y1 + t * (y2-y1)
        return (px-proj_x)**2 + (py-proj_y)**2, proj_x, proj_y

    # A. SNAP GRID POINTS
    # We modify ONLY the local geometry (x, y) of the grid points.
    # Z is already fetched. If we move X,Y, we should technically re-interpolate Z, 
    # but for "near" moves, the old Z is often "close enough" or even better (avoids artifacts).
    # Ideally, we should re-read Z from our interpolation function to be precise.
    
    # A. SNAP GRID POINTS & CLASSIFY VERTICES
    # 0 = OUTSIDE (Natural Terrain)
    # 1 = ON BOUNDARY (Shared)
    # 2 = INSIDE (Excavated Floor)
    vertex_type = [0] * len(grid_points)
    
    snapped_grid_points = [p[:] for p in grid_points] # Copy
    SNAP_THRESHOLD_MSQ = (GRID_SPACING_METERS * 0.6) ** 2  # Approx 30m
    
    # Pre-calc meter conversion factors
    lat_factor = 111132
    # lon_factor unused locally but good for reference
    
    for i, pt in enumerate(snapped_grid_points):
        # 1. Snap Check
        best_dist = 999999999
        best_proj = None
        
        px, py = pt
        
        for k in range(3):
            s = perimeter[k]
            e = perimeter[(k+1)%3]
            
            d2_deg, proj_x, proj_y = dist_sq_point_segment(px, py, s[0], s[1], e[0], e[1])
            d2_m = d2_deg * (lat_factor**2)
            
            if d2_m < SNAP_THRESHOLD_MSQ:
                if d2_m < best_dist:
                    best_dist = d2_m
                    best_proj = [proj_x, proj_y]

        if best_proj:
            snapped_grid_points[i] = best_proj
            vertex_type[i] = 1 # ON BOUNDARY
        else:
            # 2. Inside Check (if not snapped)
            if point_in_triangle(pt, V1, V2, V3):
                vertex_type[i] = 2 # INSIDE
            else:
                vertex_type[i] = 0 # OUTSIDE

    # B. EXPLICIT TRIANGULATION (STRICT FILTERING)
    terrain_i, terrain_j, terrain_k = [], [], []
    floor_i, floor_j, floor_k = [], [], []
    
    final_x = [p[0] for p in snapped_grid_points]
    final_y = [p[1] for p in snapped_grid_points]
    
    # Z Arrays
    natural_z = [z if z is not None else 0 for z in all_elevations]
    floor_z_vals = [z if z is not None else 0 for z in all_elevations]
    
    # Force Z=30 for INSIDE points (just for data consistency, though we filter triangles)
    for i in range(len(floor_z_vals)):
        if vertex_type[i] == 2: # INSIDE
             floor_z_vals[i] = CUT_LEVEL_Z
        if vertex_type[i] == 1: # ON BOUNDARY - Floor needs 30 here too
             floor_z_vals[i] = CUT_LEVEL_Z

    # Generate Indices
    for r in range(grid_rows - 1):
        for c in range(grid_cols - 1):
            # Quad Indices
            i00 = r * grid_cols + c
            i01 = r * grid_cols + (c + 1)
            i10 = (r + 1) * grid_cols + c
            i11 = (r + 1) * grid_cols + (c + 1)
            
            # Skip invalid data
            if natural_z[i00] == 0: continue 

            # Define 2 triangles
            tris = [
                (i00, i10, i11),
                (i00, i11, i01)
            ]
            
            for (idx1, idx2, idx3) in tris:
                t1, t2, t3 = vertex_type[idx1], vertex_type[idx2], vertex_type[idx3]
                types = [t1, t2, t3]
                
                # --- TERRAIN RULES ---
                # Must NOT assume any INSIDE vertices.
                # Allowed: All OUT, or OUT+ON.
                # Rejected: Any IN.
                if 2 not in types:
                    terrain_i.append(idx1)
                    terrain_j.append(idx2)
                    terrain_k.append(idx3)
                
                # --- FLOOR RULES ---
                # Must NOT assume any OUTSIDE vertices.
                # Allowed: All IN, or IN+ON.
                # Rejected: Any OUT.
                if 0 not in types:
                    floor_i.append(idx1)
                    floor_j.append(idx2)
                    floor_k.append(idx3)
                
                # Note: Triangles with mixed IN and OUT (without ON intervention) are DISCARDED.
                # This creates the necessary "gap" for the vertical wall.

    stats = {
        "cut_level": CUT_LEVEL_Z,
        "cut_volume_m3": total_cut_volume,
        "hex_wall": hex_wall_data 
    }
    
    # Custom Save for Indexed Mesh
    js_content = f"""
// Auto-generated by generate_terrain_alternative.py (Indexed Mesh)
const TERRAIN_MESH_DATA = {{
    x: {json.dumps(final_x)},
    y: {json.dumps(final_y)},
    z_natural: {json.dumps(natural_z)},
    z_floor: {json.dumps(floor_z_vals)},
    
    // INDICES (To define topology explicitly and avoid spilling)
    terrain_i: {json.dumps(terrain_i)},
    terrain_j: {json.dumps(terrain_j)},
    terrain_k: {json.dumps(terrain_k)},
    
    floor_i: {json.dumps(floor_i)},
    floor_j: {json.dumps(floor_j)},
    floor_k: {json.dumps(floor_k)},
    
    wall_x: [], wall_y: [], wall_z: [],
    
    hex_x: {json.dumps(hex_wall_data['x'])},
    hex_y: {json.dumps(hex_wall_data['y'])},
    hex_z: {json.dumps(hex_wall_data['z'])},
    
    stats: {json.dumps(stats)}
}};
"""
    try:
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(js_content)
    except Exception as e:
        print(f"  ⚠ Failed to update JS: {e}")
    
    print(f"\nDONE. Saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
