import requests
import json
import time
import math
import os

# --- CONFIG ---
OUTPUT_FILE = 'perimeter_3d_data.js'
STEP_METERS = 50  # Resolution of the path

# Vertices (Lon, Lat) from logic
V1 = (-75.25695083552709, -15.165498334382889) # NE
V2 = (-75.26825393885237, -15.172534472456562) # NW
V3 = (-75.23798892224755, -15.197477563030073) # S

# --- 1. GEOMETRY HELPERS ---
def haversine_distance(pt1, pt2):
    R = 6371000
    lon1, lat1 = map(math.radians, pt1)
    lon2, lat2 = map(math.radians, pt2)
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = math.sin(dlat/2)**2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon/2)**2
    c = 2 * math.asin(math.sqrt(a))
    return R * c

def interpolate_line(start, end, step_m):
    dist = haversine_distance(start, end)
    steps = int(dist // step_m)
    points = []
    for i in range(steps + 1):
        t = i / steps if steps > 0 else 0
        lon = start[0] + (end[0] - start[0]) * t
        lat = start[1] + (end[1] - start[1]) * t
        points.append((lon, lat))
    return points

# --- 2. API HELPERS ---
def get_elevation_open_elevation(points, pause=0.5):
    """Robust POST request to Open-Elevation."""
    results = []
    chunk_size = 150 # POST allows more
    
    for i in range(0, len(points), chunk_size):
        chunk = points[i:i+chunk_size]
        payload = {"locations": [{"latitude": p[1], "longitude": p[0]} for p in chunk]}
        
        try:
            r = requests.post("https://api.open-elevation.com/api/v1/lookup", json=payload, headers={'Content-Type': 'application/json'}, timeout=30)
            if r.status_code == 200:
                data = r.json()
                # Extract 'elevation' from results
                chunk_z = [item['elevation'] for item in data['results']]
                results.extend(chunk_z)
                print(f"  Existing Open-Elevation chunk {i} OK.")
            else:
                print(f"  Error Open-Elevation: {r.status_code}")
                # Fallback to 0
                results.extend([0]*len(chunk))
        except Exception as e:
            print(f"  Exception Open-Elevation: {e}")
            results.extend([0]*len(chunk))
            
        time.sleep(pause)
    return results

# --- 3. MAIN ---
def main():
    print("--- Generating 3D Perimeter Path ---")
    
    # Generate 2D Paths (Using logic from before)
    print(f"Interpolating lines (step={STEP_METERS}m)...")
    path_A = interpolate_line(V1, V2, STEP_METERS)
    path_B = interpolate_line(V1, V3, STEP_METERS)
    path_C = interpolate_line(V2, V3, STEP_METERS)
    
    all_points = path_A + path_B + path_C
    print(f"Total points to query: {len(all_points)}")
    
    # Fetch Z
    print("Fetching elevations from Open-Elevation...")
    z_values = get_elevation_open_elevation(all_points)
    
    # Split back results
    len_a = len(path_A)
    len_b = len(path_B)
    
    z_A = z_values[0:len_a]
    z_B = z_values[len_a:len_a+len_b]
    z_C = z_values[len_a+len_b:]
    
    # Prepare Arrays for JS
    # Structure: { side_a: {x:[], y:[], z:[]}, ... }
    
    # Helper to separate x, y
    def split_coords(pts): return ([p[0] for p in pts], [p[1] for p in pts])
    
    ax, ay = split_coords(path_A)
    bx, by = split_coords(path_B)
    cx, cy = split_coords(path_C)
    
    js_content = f"""
// Auto-generated by generate_perimeter_3d.py
// Source: Open-Meteo
const PERIMETER_3D_DATA = {{
    side_a: {{ x: {json.dumps(ax)}, y: {json.dumps(ay)}, z: {json.dumps(z_A)} }},
    side_b: {{ x: {json.dumps(bx)}, y: {json.dumps(by)}, z: {json.dumps(z_B)} }},
    side_c: {{ x: {json.dumps(cx)}, y: {json.dumps(cy)}, z: {json.dumps(z_C)} }},
    metadata: {{ "step_m": {STEP_METERS}, "date": "{time.strftime('%Y-%m-%d %H:%M')}" }}
}};
"""
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
        
    print(f"Success! Saved to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
