
import numpy as np
from scipy.spatial import Delaunay
import json
import re
import os

# Configuration
NATURAL_FILE_SOURCE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_natural.js'
CUT_FILE_SOURCE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_cut.js'
OUTPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_natural_expanded.js'

def parse_js_arrays(filepath):
    """Simple parser for JS files containing x, y, z arrays."""
    print(f"Reading {filepath}...")
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    def get_arr(axis):
        pattern = rf"{axis}\s*:\s*\[(.*?)\]"
        match = re.search(pattern, content, re.DOTALL)
        if not match: return None
        raw_vals = match.group(1).replace('\n', '').split(',')
        def safe_float(v):
            v = v.strip()
            if not v or v.lower() == 'null': return np.nan
            return float(v)
        return np.array([safe_float(v) for v in raw_vals if v.strip()])

    z_arr = get_arr('z')
    if z_arr is None:
        z_arr = get_arr('z_natural')
    if z_arr is None:
        z_arr = get_arr('intensity')

    return {
        'x': get_arr('x'),
        'y': get_arr('y'),
        'z': z_arr
    }

def main():
    # 1. Load Data
    nat_data = parse_js_arrays(NATURAL_FILE_SOURCE)
    
    # Reload Cut data manually to be sure about the keys
    with open(CUT_FILE_SOURCE, 'r', encoding='utf-8') as f:
        cut_content = f.read()
    
    def get_arr_local(axis, content):
        pattern = rf"{axis}\s*:\s*\[(.*?)\]"
        match = re.search(pattern, content, re.DOTALL)
        if not match: return None
        raw_vals = match.group(1).replace('\n', '').split(',')
        def safe_float(v):
            v = v.strip()
            if not v or v.lower() == 'null': return np.nan
            return float(v)
        return np.array([safe_float(v) for v in raw_vals if v.strip()])

    x_cut = get_arr_local('x', cut_content)
    y_cut = get_arr_local('y', cut_content)
    
    # Try all possible Z names for the Cut model
    z_cut = get_arr_local('z_floor', cut_content)
    if z_cut is None:
        z_cut = get_arr_local('z_natural', cut_content)
    if z_cut is None:
        z_cut = get_arr_local('z', cut_content)
        
    if nat_data['x'] is None or x_cut is None or z_cut is None:
        print(f"Error: Could not parse input files properly.")
        print(f"Nat X: {nat_data['x'] is not None}, Cut X: {x_cut is not None}, Cut Z: {z_cut is not None}")
        return

    print(f"Cut data Z sample: {z_cut[:10]}")
    print(f"Cut data Z unique: {np.unique(z_cut[:100])}")

    # 2. Filter Cut Data (Keep points that are NOT the excavation floor)
    EXCAVATION_Z = 30.0
    mask = np.abs(z_cut - EXCAVATION_Z) > 0.1 # Real terrain points
    
    x_cut_filtered = x_cut[mask]
    y_cut_filtered = y_cut[mask]
    z_cut_filtered = z_cut[mask]

    print(f"Original Natural points: {len(nat_data['x'])}")
    print(f"Points in Cut model: {len(x_cut)}")
    print(f"Found {len(x_cut_filtered)} points in Cut model that are NOT at Z={EXCAVATION_Z}")

    # 3. Combine Sets
    # Concatenate original points and filtered expansion points
    total_x = np.concatenate([nat_data['x'], x_cut_filtered])
    total_y = np.concatenate([nat_data['y'], y_cut_filtered])
    total_z = np.concatenate([nat_data['z'], z_cut_filtered])

    # Remove duplicates (optional but good for Delaunay)
    # Stack and find unique rows
    points_stacked = np.column_stack((total_x, total_y))
    # Using a tolerance for precision
    _, idx = np.unique(np.round(points_stacked, 6), axis=0, return_index=True)
    
    clean_x = total_x[idx]
    clean_y = total_y[idx]
    clean_z = total_z[idx]
    
    print(f"Final combined points: {len(clean_x)}")

    # 4. Delaunay Triangulation (Regenerate Mesh Topology)
    print("Regenerating topology (Delaunay)...")
    points_2d = np.column_stack((clean_x, clean_y))
    tri = Delaunay(points_2d)
    
    # tri.simplices contains the i, j, k indices
    i_idx = tri.simplices[:, 0]
    j_idx = tri.simplices[:, 1]
    k_idx = tri.simplices[:, 2]

    # 5. Save Output
    print(f"Saving to {OUTPUT_FILE}...")
    
    js_content = f"""
// Auto-generated by merge_natural_expanded.py
// Combined Original Natural data + High-Res surrounding terrain (non-excavated)
const TERRAIN_MESH_DATA = {{
    x: {json.dumps(clean_x.tolist())},
    y: {json.dumps(clean_y.tolist())},
    z: {json.dumps(clean_z.tolist())},
    terrain_i: {json.dumps(i_idx.tolist())},
    terrain_j: {json.dumps(j_idx.tolist())},
    terrain_k: {json.dumps(k_idx.tolist())},
    type: 'mesh3d',
    intensity: {json.dumps(clean_z.tolist())},
    colorscale: 'Earth',
    flatshading: false
}};
"""
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print("Done!")

if __name__ == "__main__":
    main()
