import json
import re
import requests
import time

# --- Config ---
INPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_3d.js'
OUTPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_3d.js'

def get_elevation_single(lat, lon, retry_count=3):
    """
    Fetch elevation for a single point with retry logic.
    """
    base_url = "https://api.open-meteo.com/v1/elevation"
    url = f"{base_url}?latitude={lat:.6f}&longitude={lon:.6f}"
    
    for attempt in range(retry_count):
        try:
            resp = requests.get(url)
            data = resp.json()
            
            if 'elevation' in data and len(data['elevation']) > 0:
                return data['elevation'][0]
            elif 'error' in data:
                print(f"    ⚠ API Error: {data.get('reason', 'Unknown')}")
                if 'limit' in str(data.get('reason', '')).lower():
                    print(f"    ⏸ Rate limit. Waiting 60s...")
                    time.sleep(60)
                    continue
            else:
                print(f"    ⚠ Unexpected response: {data}")
                return 0
                
        except Exception as e:
            print(f"    ⚠ Request failed (attempt {attempt+1}/{retry_count}): {e}")
            time.sleep(5)
    
    print(f"    ✗ Failed after {retry_count} attempts")
    return 0

def main():
    print("=" * 60)
    print("PATCH ZERO ELEVATIONS - DATASET 3D")
    print("=" * 60)
    
    # 1. Read current JS file
    print(f"\n📂 Reading: {INPUT_FILE}")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 2. Extract data using regex
    x_match = re.search(r'x:\s*(\[.*?\])', content, re.DOTALL)
    y_match = re.search(r'y:\s*(\[.*?\])', content, re.DOTALL)
    z_match = re.search(r'z:\s*(\[.*?\])', content, re.DOTALL)
    
    if not (x_match and y_match and z_match):
        print("✗ ERROR: Could not parse JS file")
        return
    
    x_coords = json.loads(x_match.group(1))
    y_coords = json.loads(y_match.group(1))
    z_coords = json.loads(z_match.group(1))
    
    total_points = len(z_coords)
    print(f"✓ Loaded {total_points} points")
    
    # 3. Find zero indices
    zero_indices = [i for i, z in enumerate(z_coords) if z == 0]
    zero_count = len(zero_indices)
    
    print(f"\n🔍 Found {zero_count} points with elevation = 0")
    
    if zero_count == 0:
        print("✓ No zeros to patch. Dataset is complete!")
        return
    
    print(f"\n{'='*60}")
    print(f"PATCHING {zero_count} ZERO VALUES")
    print(f"{'='*60}\n")
    
    # 4. Query API for each zero point
    patched_count = 0
    failed_count = 0
    
    for idx in zero_indices:
        lon = x_coords[idx]
        lat = y_coords[idx]
        
        print(f"Point {idx+1}/{total_points} (Lon: {lon:.5f}, Lat: {lat:.5f})")
        
        elevation = get_elevation_single(lat, lon)
        
        if elevation > 0:
            z_coords[idx] = elevation
            patched_count += 1
            print(f"  ✓ Patched: {elevation:.1f} m")
        else:
            failed_count += 1
            print(f"  ✗ Still zero (API failed)")
        
        # Polite delay
        time.sleep(2)
        print()
    
    # 5. Summary
    print(f"{'='*60}")
    print(f"PATCH SUMMARY")
    print(f"{'='*60}")
    print(f"Total Zeros:     {zero_count}")
    print(f"Patched:         {patched_count}")
    print(f"Still Zero:      {failed_count}")
    print(f"Final Valid:     {len([z for z in z_coords if z > 0])} / {total_points}")
    print(f"{'='*60}\n")
    
    # 6. Update JS file
    if patched_count > 0:
        # Rebuild JS content
        js_content = f"""
// Auto-generated by generate_terrain_mesh.py
// Patched by patch_zero_elevations.py on {time.strftime('%Y-%m-%d %H:%M:%S')}
// Total Points: {total_points} | Valid: {len([z for z in z_coords if z > 0])} | Zeros: {failed_count}
const TERRAIN_MESH_DATA = {{
    x: {json.dumps(x_coords)},
    y: {json.dumps(y_coords)},
    z: {json.dumps(z_coords)},
    type: 'mesh3d',
    intensity: {json.dumps(z_coords)},
    colorscale: 'Earth'
}};
"""
        
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            f.write(js_content)
        
        print(f"✓ Saved patched dataset to: {OUTPUT_FILE}\n")
    else:
        print("⚠ No patches applied. File not modified.\n")

if __name__ == "__main__":
    main()
