
import numpy as np
from scipy.interpolate import griddata
import json
import re
import os

# Configuration
CUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_cut.js'
NATURAL_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_natural.js'
OUTPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_natural_patched.js'

def parse_js_mesh_full(filepath):
    """Parses the JS file and extracts all keys with their arrays/values."""
    print(f"Reading {filepath}...")
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # We want to find ALL keys in the object
    # Format: key: [ ... ] or key: value
    
    # 1. Strip the JS variable declaration to leave just the object if possible
    # Or just use regex to find all matches of "key: value"
    
    # Regex for "key: ["
    # We'll use a more surgical approach to get everything
    pattern = r'(\w+)\s*:\s*(.*?)(?:,\s*\n\s*\w+\s*:|\s*};)'
    # This is tricky due to nested arrays. 
    # Let's try a simpler approach: extract specific keys we know exist.
    
    keys = ['x', 'y', 'z', 'z_natural', 'z_floor', 'terrain_i', 'terrain_j', 'terrain_k', 
            'floor_i', 'floor_j', 'floor_k', 'wall_x', 'wall_y', 'wall_z', 'hex_x', 'hex_y', 'hex_z']
    
    data = {}
    for key in keys:
        # Match axis: [ ... ], or axis: [...]
        match = re.search(rf"{key}\s*:\s*\[(.*?)\]", content, re.DOTALL)
        if match:
            raw_vals = match.group(1).replace('\n', '').split(',')
            def safe_float(v):
                v = v.strip()
                if not v or v.lower() == 'null':
                    return np.nan
                return float(v)
            vals = [safe_float(v) for v in raw_vals if v.strip()]
            data[key] = np.array(vals)
            
    # Also look for non-array stats if any
    stats_match = re.search(r'stats\s*:\s*({.*?})', content, re.DOTALL)
    if stats_match:
        try:
            data['stats'] = json.loads(stats_match.group(1).replace("'", '"'))
        except:
            pass
            
    return data

def save_js_mesh_full(filepath, data):
    """Saves the full mesh data object to a JS file."""
    print(f"Saving to {filepath}...")
    
    # Convert all numpy arrays to lists for JSON
    json_data = {}
    for k, v in data.items():
        if isinstance(v, np.ndarray):
            json_data[k] = np.nan_to_num(v).tolist()
        else:
            json_data[k] = v
            
    # Format as JS
    # Using json.dumps is fine for arrays
    lines = []
    for k, v in json_data.items():
        val_str = json.dumps(v)
        lines.append(f"    {k}: {val_str}")
        
    js_content = f"""
// Auto-generated by patch_z_natural.py
// HIGH RESOLUTION NATURAL TERRAIN (No excavation)
const TERRAIN_MESH_DATA = {{
{',\n'.join(lines)}
}};
"""
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(js_content)
    print("File saved successfully.")

def main():
    # 1. Load Data
    full_cut_data = parse_js_mesh_full(CUT_FILE)
    
    # For source Z, we need the low-res natural file
    # We reuse the simple parser for the source
    with open(NATURAL_FILE, 'r', encoding='utf-8') as f:
        nat_content = f.read()
    
    def get_arr(axis, content):
        m = re.search(rf"{axis}\s*:\s*\[(.*?)\]", content, re.DOTALL)
        if not m: return None
        return np.array([float(v.strip()) for v in m.group(1).replace('\n', '').split(',') if v.strip()])

    x_nat = get_arr('x', nat_content)
    y_nat = get_arr('y', nat_content)
    z_nat = get_arr('z', nat_content)
    
    if x_nat is None or y_nat is None or z_nat is None:
        print("Failed to load source Natural data.")
        return

    # 2. Interpolate
    points_src = np.column_stack((x_nat, y_nat))
    grid_x = full_cut_data['x']
    grid_y = full_cut_data['y']
    
    print(f"Interpolating Natural Z onto grid of {len(grid_x)} points...")
    z_new = griddata(points_src, z_nat, (grid_x, grid_y), method='linear')
    
    # Fill NAs
    nan_mask = np.isnan(z_new)
    if np.any(nan_mask):
        z_nearest = griddata(points_src, z_nat, (grid_x, grid_y), method='nearest')
        z_new[nan_mask] = z_nearest[nan_mask]
        
    # 3. Patch the data
    # We want the Natural terrain model to show the Natural surface
    # So we replace 'z' and 'z_natural'
    full_cut_data['z'] = z_new
    full_cut_data['z_natural'] = z_new
    # We can also set intensity for Plotly
    full_cut_data['intensity'] = z_new 
    
    # 4. Save
    save_js_mesh_full(OUTPUT_FILE, full_cut_data)

if __name__ == "__main__":
    main()
