
// Auto-generated by analyze_perimeter_sides.py
const PERIMETER_SIDES_GEOJSON = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "name": "Lado A (Extensi\u00f3n): 1.44 km",
                "side_id": "A",
                "length_km": 1.44,
                "description": "Extensi\u00f3n Ruta Verde",
                "stroke": "#10b981"
            },
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        -75.25695083552709,
                        -15.165498334382889
                    ],
                    [
                        -75.26825393885237,
                        -15.172534472456562
                    ]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "name": "Lado B (Este): 4.10 km",
                "side_id": "B",
                "length_km": 4.1,
                "description": "L\u00edmite Este (Tierra)",
                "stroke": "#f59e0b"
            },
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        -75.25695083552709,
                        -15.165498334382889
                    ],
                    [
                        -75.23798892224755,
                        -15.197477563030073
                    ]
                ]
            }
        },
        {
            "type": "Feature",
            "properties": {
                "name": "Lado C (Oeste): 4.27 km",
                "side_id": "C",
                "length_km": 4.27,
                "description": "Frente al Mar",
                "stroke": "#3b82f6"
            },
            "geometry": {
                "type": "LineString",
                "coordinates": [
                    [
                        -75.26825393885237,
                        -15.172534472456562
                    ],
                    [
                        -75.23798892224755,
                        -15.197477563030073
                    ]
                ]
            }
        }
    ]
};
