import json
import re
import time

# --- Config ---
INPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_3d.js'
OUTPUT_FILE = r'C:\Users\rguti\Petral.MARK\Dashboard_Puertos\terrain_mesh_3d.js'

def main():
    print("=" * 60)
    print("REMOVE ZERO ELEVATIONS - CLEAN DATASET")
    print("=" * 60)
    
    # 1. Read current JS file
    print(f"\n📂 Reading: {INPUT_FILE}")
    with open(INPUT_FILE, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 2. Extract data using regex
    x_match = re.search(r'x:\s*(\[.*?\])', content, re.DOTALL)
    y_match = re.search(r'y:\s*(\[.*?\])', content, re.DOTALL)
    z_match = re.search(r'z:\s*(\[.*?\])', content, re.DOTALL)
    
    if not (x_match and y_match and z_match):
        print("✗ ERROR: Could not parse JS file")
        return
    
    x_coords = json.loads(x_match.group(1))
    y_coords = json.loads(y_match.group(1))
    z_coords = json.loads(z_match.group(1))
    
    original_count = len(z_coords)
    print(f"✓ Loaded {original_count} points")
    
    # 3. Filter out zeros
    print(f"\n🔍 Filtering out points with elevation = 0...")
    
    filtered_x = []
    filtered_y = []
    filtered_z = []
    
    removed_count = 0
    
    for i in range(len(z_coords)):
        if z_coords[i] > 0:
            filtered_x.append(x_coords[i])
            filtered_y.append(y_coords[i])
            filtered_z.append(z_coords[i])
        else:
            removed_count += 1
    
    final_count = len(filtered_z)
    
    # 4. Summary
    print(f"\n{'='*60}")
    print(f"FILTER SUMMARY")
    print(f"{'='*60}")
    print(f"Original Points: {original_count}")
    print(f"Removed (zeros): {removed_count}")
    print(f"Final Points:    {final_count}")
    print(f"Retention:       {100*final_count/original_count:.1f}%")
    
    if final_count > 0:
        print(f"\nAltitude Range:")
        print(f"  Min: {min(filtered_z):.1f} m")
        print(f"  Max: {max(filtered_z):.1f} m")
    
    print(f"{'='*60}\n")
    
    # 5. Update JS file
    js_content = f"""
// Auto-generated by generate_terrain_mesh.py
// Cleaned by remove_zero_points.py on {time.strftime('%Y-%m-%d %H:%M:%S')}
// Total Points: {final_count} (removed {removed_count} zeros)
const TERRAIN_MESH_DATA = {{
    x: {json.dumps(filtered_x)},
    y: {json.dumps(filtered_y)},
    z: {json.dumps(filtered_z)},
    type: 'mesh3d',
    intensity: {json.dumps(filtered_z)},
    colorscale: 'Earth'
}};
"""
    
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"✓ Saved cleaned dataset to: {OUTPUT_FILE}\n")
    print(f"🎯 Ready to visualize {final_count} valid points in 3D viewer!\n")

if __name__ == "__main__":
    main()
