const REAL_TIME_SHIPS = [
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-173",
        "name": "CHARLES ISLAND",
        "eta": "26/04/2026 06:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "GB - DOVER",
        "origin_country": "REINO UNIDO",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "FRIGORIFICO",
        "flag": "BAHAMAS",
        "length": 179.9,
        "beam": 25.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPAI",
        "movement_type": "DEPARTURE",
        "due": "PAI-2026-247",
        "name": "CENTURY EMERALD",
        "eta": "26/04/2026 14:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - SALAVERRY",
        "origin_country": "PERU",
        "terminal": "TERMINAL PORTUARIO EUROANDINO",
        "etb": "",
        "type": "GRANELERO",
        "flag": "PANAMA",
        "length": 137.03,
        "beam": 23,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01175",
        "name": "CHASE OCEAN",
        "eta": "26/04/2026 02:00:00",
        "agency": "RENADSA",
        "origin_port": "PE - ILO",
        "origin_country": "PERU",
        "terminal": "LA PAMPILLA",
        "etb": "01/01/0001 00:00:00",
        "type": "BUQUE TANQUE QUIMIQUERO",
        "flag": "LIBERIA",
        "length": 183.2,
        "beam": 32.2,
        "dwt": 46959.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01141",
        "name": "SAPPHIRE ETERNITY",
        "eta": "26/04/2026 03:00:00",
        "agency": "TRAMARSA",
        "origin_port": "BR - PRAIA MOLE",
        "origin_country": "BRASIL",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "LIBERIA",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01178",
        "name": "CAPE BRUNO",
        "eta": "26/04/2026 06:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 172,
        "beam": 27.5,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01185",
        "name": "TORM DUBAI",
        "eta": "26/04/2026 06:00:00",
        "agency": "ISS MARINE",
        "origin_port": "PE - MOLLENDO",
        "origin_country": "PERU",
        "terminal": "LA PAMPILLA",
        "etb": "-",
        "type": "BUQUE TANQUE",
        "flag": "SINGAPORE",
        "length": 183.12,
        "beam": 32.2,
        "dwt": 49990.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01176",
        "name": "GREEBA MANX",
        "eta": "26/04/2026 06:30:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "PE - ILO",
        "origin_country": "PERU",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "ISLE OF MAN",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01017",
        "name": "HIGH TRUST",
        "eta": "26/04/2026 09:00:00",
        "agency": "COSMOS",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "VALERO PER\u00da",
        "etb": "-",
        "type": "BUQUE TANQUE",
        "flag": "LIBERIA",
        "length": 183,
        "beam": 32.2,
        "dwt": 49990.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01126",
        "name": "FEDERAL IRIS",
        "eta": "26/04/2026 09:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - PUNTA PATACHE",
        "origin_country": "CHILE",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "26/04/2026 17:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 199.98,
        "beam": 32.24,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01137",
        "name": "ITAJAI EXPRESS",
        "eta": "26/04/2026 10:00:00",
        "agency": "TRAMARSA",
        "origin_port": "MX - LAZARO CARDENAS",
        "origin_country": "MEXICO",
        "terminal": "DP WORLD",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 335.12,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01148",
        "name": "ALAMO",
        "eta": "26/04/2026 12:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "CL - MICHILLA",
        "origin_country": "CHILE",
        "terminal": "BAHIA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "PANAMA",
        "length": 182.87,
        "beam": 31,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01188",
        "name": "SPL ATACAMA",
        "eta": "26/04/2026 12:30:00",
        "agency": "AGUNSA PERU",
        "origin_port": "PE - MATARANI",
        "origin_country": "PERU",
        "terminal": "APM TERMINALS",
        "etb": "30/04/2026 14:00:00",
        "type": "BUQUE GRANELERO",
        "flag": "CHILE",
        "length": 180,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01138",
        "name": "LITTLE ATHINA",
        "eta": "26/04/2026 16:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - SAN VICENTE",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "27/04/2026 02:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 171.9,
        "beam": 28.4,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01144",
        "name": "ECO SIROCCO",
        "eta": "26/04/2026 17:00:00",
        "agency": "PEREZ Y CIA PERU S.A.C",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "-",
        "type": "BUQUE CONTAINERO",
        "flag": "MALTA",
        "length": 148,
        "beam": 27.2,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "ARRIVAL",
        "due": "CLL-2026-01164",
        "name": "CLIFFORD MAERSK",
        "eta": "26/04/2026 21:00:00",
        "agency": "MAERSK LINE PER\u00da S.A.C",
        "origin_port": "CO - BUENAVENTURA",
        "origin_country": "COLOMBIA",
        "terminal": "APM TERMINALS",
        "etb": "26/04/2026 22:00:00",
        "type": "BUQUE CONTAINERO",
        "flag": "DINAMARCA",
        "length": 346.98,
        "beam": 42.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1136",
        "name": "LEONIDAS Z",
        "eta": "26/04/2026 02:00:00",
        "agency": "TRAMARSA",
        "origin_port": "PE - PAITA",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "ISLAS MARSHALL",
        "length": 185.97,
        "beam": 35,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1112",
        "name": "KOTA SANTOS",
        "eta": "26/04/2026 06:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 333.99,
        "beam": 42.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1113",
        "name": "HUAN HANG 17",
        "eta": "26/04/2026 11:00:00",
        "agency": "TRAMARSA",
        "origin_port": "CN - FANGCHENG",
        "origin_country": "CHINA",
        "terminal": "TRANSPORTADORA CALLAO",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "ISLAS MARSHALL",
        "length": 189.96,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-846",
        "name": "ECCE HOMO DIVINO",
        "eta": "26/04/2026 14:00:00",
        "agency": "TRANSPERU",
        "origin_port": "XZ - INTERNATIONAL WATERS",
        "origin_country": "AGUAS INTERNACIONALES",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "PESQUERO",
        "flag": "ESPA\u00d1A",
        "length": 31.87,
        "beam": 8.1,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1151",
        "name": "GOLDEN THETIS",
        "eta": "26/04/2026 15:00:00",
        "agency": "TRANSMERIDIAN",
        "origin_port": "IN - KANDLA",
        "origin_country": "INDIA",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE TANQUE QUIMIQUERO",
        "flag": "PANAMA",
        "length": 156.53,
        "beam": 25,
        "dwt": 25918.0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1134",
        "name": "EA GATUN",
        "eta": "26/04/2026 17:00:00",
        "agency": "PEREZ Y CIA PERU S.A.C",
        "origin_port": "PE - CHANCAY",
        "origin_country": "PERU",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "PORTUGAL",
        "length": 166.15,
        "beam": 25,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-913",
        "name": "HESPER",
        "eta": "26/04/2026 22:00:00",
        "agency": "TRANSPERU",
        "origin_port": "XZ - INTERNATIONAL WATERS",
        "origin_country": "AGUAS INTERNACIONALES",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "PESQUERO",
        "flag": "ESPA\u00d1A",
        "length": 40.5,
        "beam": 8.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1027",
        "name": "MSC CANDIDA",
        "eta": "26/04/2026 22:00:00",
        "agency": "MSC DEL PERU",
        "origin_port": "CL - SAN ANTONIO",
        "origin_country": "CHILE",
        "terminal": "APM TERMINALS",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 366,
        "beam": 51,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1176",
        "name": "GREEBA MANX",
        "eta": "26/04/2026 23:00:00",
        "agency": "CALLS SHIPPING",
        "origin_port": "CN - BAYUQUAN",
        "origin_country": "CHINA",
        "terminal": "BAHIA",
        "etb": "",
        "type": "BUQUE GRANELERO",
        "flag": "ISLE OF MAN",
        "length": 199.9,
        "beam": 32.26,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PECLL",
        "movement_type": "DEPARTURE",
        "due": "CLL-2026-1178",
        "name": "CAPE BRUNO",
        "eta": "26/04/2026 23:30:00",
        "agency": "TRAMARSA",
        "origin_port": "CL - IQUIQUE",
        "origin_country": "CHILE",
        "terminal": "DP WORLD",
        "etb": "",
        "type": "BUQUE CONTAINERO",
        "flag": "LIBERIA",
        "length": 172,
        "beam": 27.5,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00160",
        "name": "NAVISION VINCENTZ",
        "eta": "26/04/2026 09:00:00",
        "agency": "TRAMARSA",
        "origin_port": "AR - ZARATE",
        "origin_country": "ARGENTINA",
        "terminal": "TPP SA",
        "etb": "-",
        "type": "BUQUE GRANELERO",
        "flag": "ISLAS MARSHALL",
        "length": 179.99,
        "beam": 30,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "ARRIVAL",
        "due": "PIO-2026-00166",
        "name": "FM PROSPERITY",
        "eta": "26/04/2026 19:00:00",
        "agency": "MARITIMA B & M",
        "origin_port": "EC - GUAYAQUIL",
        "origin_country": "ECUADOR",
        "terminal": "TPP SA",
        "etb": "-",
        "type": "GENERAL CARGO VESSEL",
        "flag": "PANAMA",
        "length": 122.2,
        "beam": 19.8,
        "dwt": 0,
        "gross_tonnage": ""
    },
    {
        "port_id": "PEPIO",
        "movement_type": "DEPARTURE",
        "due": "PIO-2026-158",
        "name": "PIS FLORES",
        "eta": "26/04/2026 10:00:00",
        "agency": "ISS MARINE",
        "origin_port": "KR - YEOSU",
        "origin_country": "COREA DEL SUR",
        "terminal": "PLATAFORMA TERMINAL MARINO PISCO CAMISEA - CAMISEA",
        "etb": "",
        "type": "BUQUE TANQUE",
        "flag": "PANAMA",
        "length": 183.06,
        "beam": 32.2,
        "dwt": 49999.0,
        "gross_tonnage": ""
    }
];