-- Create the table for storing ship movements
create table public.port_arrivals (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  snapshot_date date not null,
  port_id text,
  port_name text,
  movement_type text,
  ship_due text,
  ship_name text,
  ship_type text,
  arrival_eta timestamp with time zone,
  agency text,
  terminal text,
  length double precision,
  beam double precision
);

-- Create a unique constraint to prevent duplicates for the same ship update
alter table public.port_arrivals
  add constraint port_arrivals_unique_constraint 
  unique (ship_due, snapshot_date, movement_type);

-- Enable Row Level Security (RLS)
alter table public.port_arrivals enable row level security;

-- Create policy to allow anonymous inserts/updates (since we use the API key)
create policy "Allow public insert"
on public.port_arrivals
for insert 
with check (true);

create policy "Allow public select"
on public.port_arrivals
for select
using (true);

create policy "Allow public update"
on public.port_arrivals
for update
using (true);
