-- OPTION 1: Alter existing table (If you want to keep old data)
-- ALTER TABLE public.port_arrivals ADD COLUMN movement_type TEXT DEFAULT 'ARRIVAL';

-- OPTION 2: Recreate Table (Cleaner for new constraints) -> RECOMMENDED since we just started

DROP TABLE IF EXISTS public.port_arrivals;

CREATE TABLE public.port_arrivals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    snapshot_date DATE DEFAULT CURRENT_DATE,
    
    port_id TEXT,
    port_name TEXT,
    movement_type TEXT,       -- 'ARRIVAL' or 'DEPARTURE'
    
    ship_due TEXT,            -- Nro DUE (Unique Identifier for the call)
    ship_name TEXT,
    ship_type TEXT,
    arrival_eta TIMESTAMP,    -- ETA/ETD
    agency TEXT,
    terminal TEXT,
    length FLOAT,
    beam FLOAT,
    dwt FLOAT,
    
    -- Constraint: Allows recording both Arrival and Departure for the same ship on the same day
    CONSTRAINT unique_movement_daily UNIQUE(ship_due, snapshot_date, movement_type)
);

ALTER TABLE public.port_arrivals ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read/write for all" ON public.port_arrivals
FOR ALL USING (true) WITH CHECK (true);
